[profile.default]
optimizer = true
optimizer_runs = 1000000  # Or another value like 200, 10000 etc.
via_ir = true
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.29"
auto_detect_solc = false 
# You can add other settings like optimizer later if needed
# For example:
# optimizer = true
# optimizer_runs = 200